### ISSUE TITLE
About Dataset Processing

### ISSUE THREAD

**Issue by upeng10** [KAZABANA/EEGMatch#2]
There is a line of code like this 
path='F:\\zhourushuang\\transfer_learning\\feature_for_net_session'+str(session)+'_LDS_de'
Could you explain how the file feature_for_net_session'+str(session)+'_LDS_de' is constructed? The seed and seed iv datasets do not provide this file directly.

**Comment by KAZABANA** [comment]
'F:\zhourushuang\transfer_learning\feature_for_net_session'+str(session)+'_LDS_de' is not a file. It is a folder containing LDS features from all the subjects within SEED or SEED-IV. For example, for the SEED dataset, Session 1, the folder might have 15 files. Each file contains the LDS features for each subject (a 3394 X 310 matrix, time X feature dim). For example, for subject 1 (session 1), you can construct the file by concatenating the LDS feature (a 62 X 5 -dim vector) from different trials.

**Comment by upeng10** [comment]
Thank you for your answer. I tried it, but there may still be some minor problems and it didn't work. Could you please send me the files of this part directly? I'm very sorry for the trouble.

**Comment by KAZABANA** [comment]
We have uploaded a new script (data_prepare_seed.m) for the LDS-DE dataset construction (SEED). You can prepare the dataset for SEED-IV using a similar pipeline. Thanks

**Comment by upeng10** [comment]
Thanks a lot for your work and I wish you good luck in your research!!!
